/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.1.0 Fri Aug  5 23:08:35 2022.
 */

#include <string.h>

#include "Msg.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int Msg_driver_torque_pack(
    uint8_t *dst_p,
    const struct Msg_driver_torque_t *src_p,
    size_t size)
{
    uint16_t steering_torque_driver;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    steering_torque_driver = (uint16_t)src_p->steering_torque_driver;
    dst_p[0] |= pack_left_shift_u16(steering_torque_driver, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(steering_torque_driver, 8u, 0x0fu);

    return (2);
}


int16_t Msg_driver_torque_steering_torque_driver_encode(float value)
{
    return (int16_t)(value / 0.0625f);
}

bool Msg_driver_torque_steering_torque_driver_is_in_range(int16_t value)
{
    return ((value >= -2048) && (value <= 2047));
}

int Msg_steering_command_unpack(
    struct Msg_steering_command_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t steer_angle;
    uint8_t steer_torque;

    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->checksum = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->counter = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->steer_mode = unpack_right_shift_u8(src_p[1], 4u, 0x30u);
    steer_angle = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    steer_angle |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->steer_angle = (int16_t)steer_angle;
    steer_torque = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->steer_torque = (int8_t)steer_torque;

    return (0);
}

float Msg_steering_command_checksum_decode(uint8_t value)
{
    return ((float)value);
}

bool Msg_steering_command_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

float Msg_steering_command_counter_decode(uint8_t value)
{
    return ((float)value);
}

bool Msg_steering_command_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

float Msg_steering_command_steer_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool Msg_steering_command_steer_mode_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

float Msg_steering_command_steer_angle_decode(int16_t value)
{
    return ((float)value * 0.125f);
}

bool Msg_steering_command_steer_angle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

float Msg_steering_command_steer_torque_decode(int8_t value)
{
    return ((float)value * 0.125f);
}

bool Msg_steering_command_steer_torque_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int Msg_steering_status_pack(
    uint8_t *dst_p,
    const struct Msg_steering_status_t *src_p,
    size_t size)
{
    uint16_t steering_angle;
    uint8_t steering_speed;
    uint8_t steering_torque;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->checksum, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->counter, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->control_status, 4u, 0xf0u);
    steering_torque = (uint8_t)src_p->steering_torque;
    dst_p[2] |= pack_left_shift_u8(steering_torque, 0u, 0xffu);
    steering_speed = (uint8_t)src_p->steering_speed;
    dst_p[3] |= pack_left_shift_u8(steering_speed, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->temperature, 0u, 0xffu);
    steering_angle = (uint16_t)src_p->steering_angle;
    dst_p[5] |= pack_left_shift_u16(steering_angle, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(steering_angle, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->debug_states, 0u, 0xffu);

    return (8);
}


uint8_t Msg_steering_status_checksum_encode(float value)
{
    return (uint8_t)(value);
}

bool Msg_steering_status_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Msg_steering_status_counter_encode(float value)
{
    return (uint8_t)(value);
}

bool Msg_steering_status_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t Msg_steering_status_control_status_encode(float value)
{
    return (uint8_t)(value);
}

bool Msg_steering_status_control_status_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int8_t Msg_steering_status_steering_torque_encode(float value)
{
    return (int8_t)(value / 0.125f);
}

bool Msg_steering_status_steering_torque_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t Msg_steering_status_steering_speed_encode(float value)
{
    return (int8_t)(value / 0.015625f);
}

bool Msg_steering_status_steering_speed_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

uint8_t Msg_steering_status_temperature_encode(float value)
{
    return (uint8_t)(value - -60.0f);
}

bool Msg_steering_status_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int16_t Msg_steering_status_steering_angle_encode(float value)
{
    return (int16_t)(value / 0.125f);
}

bool Msg_steering_status_steering_angle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint8_t Msg_steering_status_debug_states_encode(float value)
{
    return (uint8_t)(value);
}

bool Msg_steering_status_debug_states_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
